name: Deploy website on push

on:
  push: # This triggers the script to run on every push to the main branch
    branches:
      - main

jobs:
  admin-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use PHP # installs the specified version of php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.2'

    - name: Installing Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/compose

    - name: Installing PHP dependencies
      run: composer install

    - name: Installing Node dependencies
      run: |
        npm i
        npm run build
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Deploying project # copy files to specified FTP directory
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: | # Addind this part ensures node_modules will be deployed for the app to run
          **/.git*
          **/.git*/**
          **/.env.example
          **/.editorconfig
